name: "Ruff"

on:
  push:
    branches: [ main ]
    paths:
      - 'app_name/**/*.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'app_name/**/*.py'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruff lint
        uses: chartboost/ruff-action@v1
        with:
          args: check .
